DROP TRIGGER IF EXISTS autogen_region_id on region;
DROP FUNCTION IF EXISTS f_autogen_region_id;


/* this trigger allows region_id to be either manualy entered
or autogenerated, if not provided. To autogenerate region_id
put 0 in place of region_id on insert.
*/
CREATE OR REPLACE FUNCTION f_autogen_region_id() RETURNS TRIGGER AS
$$
DECLARE
	next_val INT;
BEGIN
	SELECT last_value FROM id_seq into next_val;
	IF NEW.region_id >= next_val THEN
		PERFORM setval('id_seq', NEW.region_id+1);
	ELSIF NEW.region_id = 0 THEN
		NEW.region_id = next_val;
	END IF;
	RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';


CREATE TRIGGER autogen_region_id
	BEFORE INSERT ON region
	FOR EACH ROW
	EXECUTE PROCEDURE f_autogen_region_id();
	



